import uuid

from sqlalchemy import Boolean, Column, ForeignKey, Index, Integer, String, Text
from sqlalchemy.dialects.postgresql import TIMESTAMP, UUID

from src.api.data.clients.postgres import Base
from src.api.utils.common_utils import utc_now


class TopicNode(Base):
    __tablename__ = "topicnodes"

    node_id = Column("nodeid", UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    space_id = Column(
        "spaceid",
        UUID(as_uuid=True),
        ForeignKey("espaces.spaceid", ondelete="RESTRICT"),
        nullable=False,
    )
    parent_id = Column(
        "parentid",
        UUID(as_uuid=True),
        ForeignKey("topicnodes.nodeid", ondelete="RESTRICT"),
        nullable=True,
    )
    title = Column(String(300), nullable=False)
    level = Column(Integer, nullable=False)
    order_index = Column("orderindex", Integer, nullable=False, default=0)
    node_specific_instruction = Column("nodespecificinstruction", Text, nullable=True)
    tree_default_instruction = Column("treedefaultinstruction", Text, nullable=True)
    node_additive_instruction = Column("nodeadditiveinstruction", Text, nullable=True)
    is_primary_learning_unit = Column(
        "isprimarylearningunit", Boolean, nullable=False, default=False
    )
    is_active = Column("isactive", Boolean, nullable=False, default=True)
    created_by = Column(
        "createdby",
        UUID(as_uuid=True),
        ForeignKey("mentors.mentorid", ondelete="RESTRICT"),
        nullable=False,
    )
    created_at = Column(
        "createdat",
        TIMESTAMP(timezone=True),
        nullable=False,
        default=utc_now,
    )
    updated_at = Column(
        "updatedat",
        TIMESTAMP(timezone=True),
        nullable=False,
        default=utc_now,
        onupdate=utc_now,
    )
    source_pdf_id = Column(
        "sourcepdfid",
        UUID(as_uuid=True),
        ForeignKey("referencematerials.materialid", ondelete="RESTRICT"),
        nullable=True,
    )
    source_section_path = Column("sourcesectionpath", Text, nullable=True)
    auto_generated = Column("autogenerated", Boolean, nullable=False, default=False)

    __table_args__ = (
        Index(
            "ix_topicnodes_space_parent_order",
            "spaceid",
            "parentid",
            "orderindex",
        ),
    )
